### ISSUE TITLE
isnt it on pip?

### ISSUE THREAD

**Issue by iogf** [serverdensity/python-daemon#25] opened 2016-05-19 06:21 UTC
how can i install it from pip?

**Comment by brezniczky** [comment] 2016-07-25 22:36
In case you are still interested, by trial-error looks like it's simply `pip install python-daemon`.
I was thinking this could be the case since it's mentioned at https://pypi.python.org/pypi/python-daemon/.

**Comment by amdei** [comment] 2016-09-24 20:54
Published. See #27 
Try this now:

    pip install py_daemon

**Comment by carlosperello** [comment] 2016-12-08 21:58
That python-daemon module on pypi is a different project.

Closing this as it's a duplicate of #17

**Closed by carlosperello** 2016-12-08 21:58 UTC
